# Granger Casuality

In [1]:
#Regression on time series analysis.
#Based on the discussion with professor Dantong Yu ,
#I need to implement the ridge, lasso, elastic regression on the time series data.
#The data is taken from the dtyu-granger-causality. 

In [20]:
import numpy as np
from scipy.io import loadmat  # this is the SciPy module that loads mat-files
import matplotlib.pyplot as plt
from datetime import datetime, date, time
import pandas as pd
from numpy.linalg import inv
mat = loadmat(r'C:\Users\dantongyu\Downloads\dtyu-granger-causality\dtyu-granger-causality-645084c3e1f5\SimulationExperiment\Ridge\analysis\lambda_1_case_study\filter_norm_expression.mat')  # load mat-file
mdata = mat['expression']
mdata=np.asmatrix(mdata)

In [22]:
len(mdata[:,3])
mdata.shape

(1000, 20)

In [31]:
mdata[:,:5]

matrix([[ 0.20917326,  0.30489817,  0.26259475, -0.10205479, -0.55465239],
        [ 0.10597167,  0.49453251, -0.06722951, -0.45352422, -0.71827714],
        [ 0.23981549, -0.11018578,  0.50018292,  1.05755325,  1.26369524],
        ...,
        [ 0.78295462,  0.69103037,  0.3373717 , -0.0368846 , -0.38448166],
        [ 0.07799073,  0.1208465 , -0.06927812, -0.41973049, -0.69267765],
        [-0.03472913, -1.04344869, -0.43308817, -0.46962836, -1.3733422 ]])

In [24]:
mdata[:,0:2]

matrix([[ 0.20917326,  0.30489817],
        [ 0.10597167,  0.49453251],
        [ 0.23981549, -0.11018578],
        ...,
        [ 0.78295462,  0.69103037],
        [ 0.07799073,  0.1208465 ],
        [-0.03472913, -1.04344869]])

In [25]:
mdata[:,3:]

matrix([[-0.10205479, -0.55465239, -0.91629071, ..., -0.51543144,
         -0.84607069, -1.13384379],
        [-0.45352422, -0.71827714, -0.64472399, ..., -0.80413433,
         -0.83236472, -0.83008514],
        [ 1.05755325,  1.26369524,  1.551796  , ..., -0.13748383,
         -0.42509869, -0.67548787],
        ...,
        [-0.0368846 , -0.38448166, -0.20084109, ...,  0.48779431,
          0.77215343,  1.23137852],
        [-0.41973049, -0.69267765, -0.89082296, ..., -0.91779605,
         -0.67734844, -0.40470891],
        [-0.46962836, -1.3733422 , -1.6085277 , ...,  0.5288358 ,
          0.05318378, -0.33220694]])

In [27]:
mdata[:,4:20]

matrix([[-0.55465239, -0.91629071, -1.12559868, ..., -0.51543144,
         -0.84607069, -1.13384379],
        [-0.71827714, -0.64472399, -1.00620094, ..., -0.80413433,
         -0.83236472, -0.83008514],
        [ 1.26369524,  1.551796  ,  1.48968684, ..., -0.13748383,
         -0.42509869, -0.67548787],
        ...,
        [-0.38448166, -0.20084109,  0.106374  , ...,  0.48779431,
          0.77215343,  1.23137852],
        [-0.69267765, -0.89082296, -0.71477305, ..., -0.91779605,
         -0.67734844, -0.40470891],
        [-1.3733422 , -1.6085277 , -0.87771077, ...,  0.5288358 ,
          0.05318378, -0.33220694]])

# Multivariate Granger Casuality model

In [81]:
import numpy as np
from scipy.io import loadmat  # this is the SciPy module that loads mat-files
import matplotlib.pyplot as plt
from datetime import datetime, date, time
import pandas as pd
from numpy.linalg import inv
mat = loadmat(r'C:\Users\dantongyu\Downloads\dtyu-granger-causality\dtyu-granger-causality-645084c3e1f5\SimulationExperiment\Ridge\analysis\lambda_1_case_study\filter_norm_expression.mat')  # load mat-file
mdata = mat['expression']
mdata=np.asmatrix(mdata)
# Here they are taking the period as 3.
# Here n_gene is nothing but the number of sensors in IOT data set.
period=3
temp=mdata.shape
n_gene=temp[0]
Time_samples=temp[1]
m=Time_samples-period
#Y is starting its values for 2000 genes from the p+1 time instant till Time
Y=mdata[:,period:Time_samples].T
# Transpose is performed by .T as mdata is a matrix and the dimensions of the Y ----> m x n as shown in the paper
# Here you take for all the variables at time t
X=np.matlib.zeros((m, n_gene*period))

for i in range(m):
    for j in range(period):
        #I have to take the large slices to run it faster
#         print(X[i,n_gene*(j):n_gene*(j+1)].shape, (mdata[:,i+period-j-1].T).shape )
        X[i,n_gene*(j):n_gene*(j+1)]=mdata[:,i+period-j-1].T
#T-2 in python is nothing but T-1 matlab notation in reality   
def ridge_regression(X,Y,lambd):
    i=X.shape[1]
    B= inv(X.T*X + lambd*np.identity(i))*X.T*Y
    return B
B=ridge_regression(X,Y,1)

In [82]:
B

matrix([[ 1.88875370e-03,  1.03049437e-03, -5.81152632e-04, ...,
         -1.42728660e-03, -1.57448314e-04, -7.05962898e-04],
        [ 2.26024620e-03,  1.93338602e-03, -1.58128823e-03, ...,
         -1.80059223e-03,  9.09563223e-04, -6.25442300e-04],
        [-2.54249065e-03, -2.91138199e-03,  4.01028619e-03, ...,
          7.97026608e-04, -2.30103356e-03, -1.17944503e-03],
        ...,
        [ 2.21168228e-04,  3.07428608e-04,  4.77321830e-04, ...,
         -1.19142851e-03,  3.66869192e-04, -2.30693134e-03],
        [ 1.13371643e-03,  6.10932112e-04, -3.07595046e-05, ...,
         -1.33472738e-03, -3.16211554e-04, -8.15122703e-04],
        [ 2.31246624e-03,  2.61543414e-03, -2.57835436e-03, ...,
         -1.81850406e-03,  1.66663016e-03, -1.11274082e-03]])

These values correspond to the output values of matlab code 0.00188875370339981 0.00103049436791531 -0.000581152631889214

# Linear Regression using time series sequence

In [75]:
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X, Y)
#Y_pred_lin = linreg.predict(X_test)
#print("Linear regression score", linreg.score(X, Y))
print("X.shape,Y.shape",X.shape,Y.shape)
# print("B Matrix and its shape",linreg.coef_,linreg.coef_.shape)
print("B in paper corresponds to ",np.transpose(linreg.coef_),"and its shape", np.transpose(linreg.coef_).shape)
#print("Root mean Square Error on the test data", np.sqrt(mean_squared_error(Y_test, Y_pred_lin)))

X.shape,Y.shape (17, 3000) (17, 1000)
B in paper corresponds to  [[ 1.65779731e-03  9.17510157e-04 -6.54011508e-04 ... -1.51265843e-03
  -1.06766501e-04 -6.77336340e-04]
 [ 2.09043660e-03  1.85053929e-03 -1.63531888e-03 ... -1.86372496e-03
   9.47124377e-04 -6.04465176e-04]
 [-2.41993251e-03 -2.85197174e-03  4.05030698e-03 ...  8.42494388e-04
  -2.32873080e-03 -1.19518266e-03]
 ...
 [ 3.40159197e-04  3.65356119e-04  5.15357763e-04 ... -1.14803175e-03
   3.40447299e-04 -2.32273477e-03]
 [ 1.15207667e-03  6.19880909e-04 -2.49897997e-05 ... -1.32808154e-03
  -3.20372241e-04 -8.17602890e-04]
 [ 2.35404484e-03  2.63618515e-03 -2.56615857e-03 ... -1.80383624e-03
   1.65801562e-03 -1.11815008e-03]] and its shape (3000, 1000)


# Ridge regression

It optimizes the following objective function

||y - Xw||^2_2 + alpha * ||w||^2_2


In [76]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1)
clf.fit(X, Y)
#print(clf.coef_)
print("B in paper corresponds to ",np.transpose(clf.coef_),"and its shape", np.transpose(clf.coef_).shape)

B in paper corresponds to  [[ 1.65754769e-03  9.17491569e-04 -6.53940650e-04 ... -1.51246795e-03
  -1.06667510e-04 -6.77249282e-04]
 [ 2.09002221e-03  1.85018841e-03 -1.63487796e-03 ... -1.86330646e-03
   9.46950273e-04 -6.04302081e-04]
 [-2.41936474e-03 -2.85120374e-03  4.04904855e-03 ...  8.42388881e-04
  -2.32807625e-03 -1.19473611e-03]
 ...
 [ 3.40108221e-04  3.65560973e-04  5.14766386e-04 ... -1.14760842e-03
   3.40745873e-04 -2.32170257e-03]
 [ 1.15204136e-03  6.19888488e-04 -2.49904716e-05 ... -1.32797607e-03
  -3.20236339e-04 -8.17398487e-04]
 [ 2.35345346e-03  2.63546680e-03 -2.56545081e-03 ... -1.80340347e-03
   1.65762795e-03 -1.11783104e-03]] and its shape (3000, 1000)


# Lasso regression 

It optimizes the following objective function

(1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1

In [77]:
from sklearn.linear_model import Lasso
clf = Lasso(alpha=1)
clf.fit(X, Y)
#print(clf.coef_)
print("B in paper corresponds to ",np.transpose(clf.coef_),"and its shape", np.transpose(clf.coef_).shape)

B in paper corresponds to  [[ 0.  0. -0. ... -0. -0. -0.]
 [ 0.  0. -0. ... -0.  0. -0.]
 [-0. -0.  0. ...  0. -0. -0.]
 ...
 [ 0.  0. -0. ... -0.  0. -0.]
 [ 0.  0. -0. ... -0.  0. -0.]
 [ 0.  0. -0. ... -0.  0. -0.]] and its shape (3000, 1000)


# Elastic net

It optimizes the following objective function

1 / (2 * n_samples) * ||y - Xw||^2_2 + alpha * l1_ratio * ||w||_1  + 0.5 * alpha * (1 - l1_ratio) * ||w||^2_2


If you are interested in controlling the L1 and L2 penalty separately, keep in mind that this is equivalent to:

a * L1 + b * L2

where:

alpha = a + b and l1_ratio = a / (a + b)


In [84]:
from sklearn.linear_model import ElasticNet
clf = Lasso(random_state=0)
clf.fit(X, Y)
#print(clf.coef_)
# If you run the command stand alone, you will get the following clf.fit(X, y) You can change those parameters if the performance is too bad.
# ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
#       max_iter=1000, normalize=False, positive=False, precompute=False,
#       random_state=0, selection='cyclic', tol=0.0001, warm_start=False)
print("B in paper corresponds to ",np.transpose(clf.coef_),"and its shape", np.transpose(clf.coef_).shape)

B in paper corresponds to  [[ 0.  0. -0. ... -0. -0. -0.]
 [ 0.  0. -0. ... -0.  0. -0.]
 [-0. -0.  0. ...  0. -0. -0.]
 ...
 [ 0.  0. -0. ... -0.  0. -0.]
 [ 0.  0. -0. ... -0.  0. -0.]
 [ 0.  0. -0. ... -0.  0. -0.]] and its shape (3000, 1000)
